# Generated by Django 6.0 on 2026-01-11 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invite_code',
            field=models.CharField(blank=True, max_length=36, null=True, unique=True),
        ),
    ]
