# Generated by Django 6.0 on 2026-01-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '1 - Very Easy'), (2, '2 - Easy'), (3, '3 - Medium'), (4, '4 - Hard'), (5, '5 - Very Hard')], default=1),
        ),
    ]
