# Generated by Django 6.0 on 2026-01-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_task_id_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('revision', 'Revision'), ('accomplished', 'Accomplishsed')], default='pending', max_length=20),
        ),
    ]
