# Generated by Django 6.0 on 2026-01-13 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_task_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
    ]
